package com.example.java_skat.game;

import pl.skat.core.Karta;

import java.util.List;

public record GameSnapshot(
        List<Karta> playerHand,
        List<Karta> currentTrick,
        List<Karta> skat,
        boolean skatVisible,
        int topOpponentCardCount,
        int leftOpponentCardCount,
        int collectedCardCount,
        GamePhase phase,
        int currentBid,
        int nextBid,
        String highestBidderName,
        String contractName,
        int cardsToDiscard,
        boolean canTakeSkatBeforeContract,
        boolean canChooseGameWithoutSkat,
        boolean declarationsRestrictedAfterSkat,
        boolean handRequired,
        boolean canBid,
        boolean canConfirmContract,
        boolean canDiscard,
        boolean canPlay,
        boolean canPass,
        boolean canNewDeal,
        String status,
        boolean finished,
        int dealNumber,
        int totalDeals,
        String playerPositionName,
        String positionSummary
) {
    public GameSnapshot(
            List<Karta> playerHand,
            List<Karta> currentTrick,
            List<Karta> skat,
            boolean skatVisible,
            int topOpponentCardCount,
            int leftOpponentCardCount,
            int collectedCardCount,
            GamePhase phase,
            int currentBid,
            int nextBid,
            String highestBidderName,
            String contractName,
            int cardsToDiscard,
            boolean canTakeSkatBeforeContract,
            boolean canChooseGameWithoutSkat,
            boolean declarationsRestrictedAfterSkat,
            boolean handRequired,
            boolean canBid,
            boolean canConfirmContract,
            boolean canDiscard,
            boolean canPlay,
            boolean canPass,
            boolean canNewDeal,
            String status,
            boolean finished
    ) {
        this(
                playerHand,
                currentTrick,
                skat,
                skatVisible,
                topOpponentCardCount,
                leftOpponentCardCount,
                collectedCardCount,
                phase,
                currentBid,
                nextBid,
                highestBidderName,
                contractName,
                cardsToDiscard,
                canTakeSkatBeforeContract,
                canChooseGameWithoutSkat,
                declarationsRestrictedAfterSkat,
                handRequired,
                canBid,
                canConfirmContract,
                canDiscard,
                canPlay,
                canPass,
                canNewDeal,
                status,
                finished,
                1,
                1,
                "tryb lokalny",
                "Tryb lokalny: pozycje przodka, środka i zadka nie są używane."
        );
    }
}
